CREATE DATABASE IF NOT EXISTS UserDB;
CREATE DATABASE IF NOT EXISTS HistoryDB;
CREATE DATABASE IF NOT EXISTS MessageDB;
USE UserDB;

DROP TABLE IF EXISTS User;

-- Create the User table
CREATE TABLE IF NOT EXISTS User (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  dateJoined DATE NOT NULL,
  type INT NOT NULL,
  profileImageURL VARCHAR(255)
);

USE HistoryDB;
DROP TABLE IF EXISTS History;
-- Create the History table
CREATE TABLE IF NOT EXISTS History (
  historyId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  postId INT NOT NULL,
  viewDate DATE NOT NULL
);

USE MessageDB;
DROP TABLE IF EXISTS Message;
-- Create the Message table
CREATE TABLE IF NOT EXISTS Message (
  messageId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  email VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  dateCreated DATE NOT NULL,
  status VARCHAR(255) NOT NULL
);
